### ISSUE TITLE
关于宁夏广电CDN直播源中的两个“未知”电视台

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#11]
宁夏广电CDN直播源中的标记为“未知”两个电视台分别是石嘴山市平罗县电视台（4200900265）和固原市泾源县电视台（4200900264）
请有空加上频道的名称，谢谢！
P.S.:香港某服务器的直播源这两天又恢复了，将域名“xiaoyu.speedws.com”改成IP地址“59.124.75.156”即可。频道地址不变，但播放的频道略有变化。

**Comment by SPX372928** [comment]
感谢！已更新
