### ISSUE TITLE
长江云的一些湖北本地电视台

### ISSUE THREAD

**Issue by ag2s20150909** [SPX372928/MyIPTV#13]
通过
[http://app.cjyun.org/video/player/streamlist?site_id=%d&live_type=1](http://app.cjyun.org/video/player/streamlist?site_id=%d&live_type=1)
查询得到的，siteid举例：10008
http://app.cjyun.org/video/player/streamlist?site_id=10008&live_type=1

CCTV-6,http://183.207.249.15/PLTV/3/224/3221225548/index.m3u8
丹江口生活频道,https://p2bj.weizan.cn/309104/751799777014582046/live.m3u8
丹江口新闻频道,http://p4.weizan.cn/15701/735957243163088440/live.m3u8
仙桃新闻综合频道,http://221.233.242.239:280/live/71/playlist.m3u8
公安人民广播电台,http://gongan.live.tempsource.cjyun.org/videotmp/10088-gatv2.m3u8
公安生活频道,http://gongan.live.tempsource.cjyun.org/videotmp/s10088-gatv3.m3u8
公安综合频道,http://gongan.live.tempsource.cjyun.org/videotmp/10088-gatv1.m3u8
兴山综合,http://play.hbxstv.com/live/xstv123.m3u8
利川综合频道,http://lichuan.live.tempsource.cjyun.org/videotmp/s10093-lczh.m3u8
咸丰影视频道,http://xianfeng.live.tempsource.cjyun.org/videotmp/s10096-xftv2.m3u8
咸丰新闻综合频道,http://xianfeng.live.tempsource.cjyun.org/videotmp/s10096-xftv1.m3u8
咸宁公共,http://xianning.live.cjyun.org/video/s10140-XNTV-1.m3u8
咸宁综合,http://xianning.live.cjyun.org/video/s10140-XNGG.m3u8
团风综合,http://tuanfeng.live.tempsource.cjyun.org/videotmp/s10113-tftv2.m3u8
大冶一套,http://dayeyun.live.tempsource.cjyun.org/videotmp/s10102-TC1T.m3u8
大冶二套,http://dayeyun.live.tempsource.cjyun.org/videotmp/s10102-TC2T.m3u8
大悟综合频道,http://yunshangdawu.live.tempsource.cjyun.org/videotmp/s10129-dwyspd.m3u8
孝感公共生活频道,http://xiaogan.source.cjyun.org/video/s10139-shpd.m3u8
孝感新闻,http://xiaogan.live.cjyun.org/video/s10139-shpd/index.m3u8
孝感新闻综合频道,http://xiaogan.live.cjyun.org/video/s10139-xg/index.m3u8
孝感公共频道,http://xiaogan.live.cjyun.org/video/s10139-shpd/index.m3u8
孝感生活频道-test,http://xiaogan.live.cjyun.org/video/s10139-shpd/index.m3u8
孝昌新闻频道,http://xiaochang.live.cjyun.org/video/s10128-xcxw/index.m3u8
孝昌生活频道,http://xiaochang.live.cjyun.org/video/s10128-xcsh/index.m3u8
宜昌综合频道,http://yichang-live21.cjyun.org/cjyun/s10091-yczh.m3u8?auth_key=1625068799-0-0-ab5a6b50a04e4495b64470353eefa003
宜昌公共频道,http://yichang-live21.cjyun.org/cjyun/s10091-ycgg.m3u8?auth_key=1625068799-0-0-af174f09e6e2a65a9cd79db6265da6fb
宜昌旅游生活,http://yichang-live21.cjyun.org/cjyun/s10091-ycly.m3u8?auth_key=1625068799-0-0-431a0ff1feab44c4a39aab7f7749793c
宣恩综合频道,http://xuanen.live.tempsource.cjyun.org/videotmp/s10097-xezh2.m3u8
广水新闻频道,http://guangshui.live.tempsource.cjyun.org/videotmp/s10146-GSXW.m3u8
应城人民广播电台,http://yingcheng.fmlive.cjyun.org/audio/s10135-YCRM/index.m3u8
应城新闻党建频道,http://yingcheng.live.cjyun.org/video/s10135-YCZH/index.m3u8
应城生活频道,http://yingcheng.live.cjyun.org/video/s10135-YCDJ/index.m3u8
当阳电视台,http://dangyang.live.tempsource.cjyun.org/videotmp/s10118-DYZH.m3u8
当阳电视台,http://dangyang.live.tempsource.cjyun.org/videotmp/s10118-DYZH.m3u8
武穴综合,http://wuxue.live.cjyun.org/video/s10107-wxtv1/index.m3u8
红安电视台,http://hongan.live.cjyun.org/video/s10063-HAZH.m3u8
后首综合频道,http://sstvplay.ssgdlive.com/live/sszh.m3u8
后首影视频道,http://sstvplay.ssgdlive.com/live/sszh2.m3u8
罗田旅游,http://luotian.live.cjyun.org/video/s10013-LTLY.m3u8
罗田综合,http://luotian.live.cjyun.org/video/s10013-LTZH.m3u8
蕲春旅游养生频道,http://qichun.live.cjyun.org/video/s10126-TC2T/index.m3u8
蕲春综合频道,http://qichun.live.cjyun.org/video/s10126-TC1T/index.m3u8
襄阳公共频道,http://xiangyang.live.cjyun.org/video/s10125-education_hd/index.m3u8
襄阳经济生活频道,http://xiangyang.live.cjyun.org/video/s10125-society_hd/index.m3u8
襄阳综合广播党风政风热线,http://live.muzhifm.com/shuazhibo/room247_pc.m3u8?auth_key=1614216526-0-0-6fa87acbfcec3365d9ca6f2e4be8ce93
襄阳综合频道,http://xiangyang.live.cjyun.org/video/s10125-news_hd/index.m3u8
襄阳频道2,http://xiangyang.live.cjyun.org/video/s10125-news_hd/index.m3u8
远安电视台,http://yuanan.live.tempsource.cjyun.org/videotmp/s10106-yatv.m3u8
鄂州公共,http://ezhou.live.cjyun.org/video/s10098-EZ1T.m3u8
鄂州新闻综合,http://ezhou.live.cjyun.org/video/s10098-EZ2T.m3u8
长阳电视台,http://changyang.live.cjyun.org/video/s10114-cy1t/index.m3u8
长阳电视台-1,http://changyang.live.cjyun.org/video/s10114-cy1t.m3u8
随州农村,http://suizhou.source.cjyun.org/video/s10145-szncpd.m3u8
随州综合,http://suizhou.source.cjyun.org/video/s10145-szzhpd.m3u8
黄冈广播电视台公共频道,http://huanggang.live.cjyun.org/video/s10120-xwgg.m3u8
黄冈广播电视台新闻综合频道,http://huanggang.live.cjyun.org/video/s10120-xwzh.m3u8

**Comment by SPX372928** [comment]
感谢！已更新
