### ISSUE TITLE
四川电信绵阳IP版 频道ID标记混乱

### ISSUE THREAD

**Issue by abc1763613206** [SPX372928/MyIPTV#16]
相关文件：https://github.com/SPX372928/MyIPTV/blob/master/%E5%9B%9B%E5%B7%9D%E7%94%B5%E4%BF%A1%E7%BB%B5%E9%98%B3ip%E7%89%88.txt

因为现在在整理[自用直播源](https://github.com/abc1763613206/myiptv)，所以干脆把这些源挨个`ffplay`验了遍。

这个源的标注比较混乱，比如`熊猫新闻`中混进了`CCTV`系，而`CCTV`中的一些变成了测试频道。
还望抽空重新扫一下，毕竟这个源质量挺高，还没屏蔽省外，挺不容易的。

**Comment by SPX372928** [comment]
这套相邻两个ip的id一样，两两一组，我慢慢弄
先放两个ip的爱上4K
爱上4K 21M2160,http://118.123.60.5:8114/LIVES/Fsv_otype=1&FvSeid=&Fsv_chan_hls_se_idx=037&Provider_id=&Pcontent_id=index.m3u8
爱上4K 21M2160,http://118.123.60.5:8114/LIVES/Fsv_otype=1&FvSeid=&Fsv_chan_hls_se_idx=107&Provider_id=&Pcontent_id=index.m3u8
爱上4K 21M2160,http://118.123.60.6:8114/LIVES/Fsv_otype=1&FvSeid=&Fsv_chan_hls_se_idx=037&Provider_id=&Pcontent_id=index.m3u8
爱上4K 21M2160,http://118.123.60.6:8114/LIVES/Fsv_otype=1&FvSeid=&Fsv_chan_hls_se_idx=107&Provider_id=&Pcontent_id=index.m3u8

**Comment by SPX372928** [comment]
已更新
