### ISSUE TITLE
大连天途有线accesstoken更新了

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#19]
大连天途有线CDN更新了accesstoken，原来那个accesstoken不能用了
新的accesstoken是：R5E03E8B3U31901110K77751E76I853CE172PBM3231086V1044EZ33519WE5878B1D031
另外有时间最好重新扫下源，好像辽宁几个省级地方台上高清版的了

**Comment by SPX372928** [comment]
已更新，感谢！不过没上高清
