### ISSUE TITLE
移动的凤凰台都是720的了，老哥我给你个1080的吧

### ISSUE THREAD

**Issue by qwerttvv** [SPX372928/MyIPTV#2]
http://220.201.218.82:65530/live/fhzx/index.m3u8
http://220.201.218.82:65530/live/fhzw/index.m3u8

就是码率大概9M的意思，这黑龙江哈尔滨联通的ip目测稳了好久了，还有别的一些台也是这个地址

**Comment by SPX372928** [comment]
测试可用！感谢！

**Comment by qwerttvv** [comment]
> 测试可用！感谢！

甭客气，一起加油儿一起玩儿

**Comment by benjaminzhou1122** [comment]
你好，你回邮件是不是按了回复所有人什么的，我收到好几个邮件。。。




钟红卫
广东体育职业技术学院


 联系我









&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"qwerttvv"<notifications@github.com&gt;;
发送时间:&nbsp;2020年6月29日(星期一) 中午11:05
收件人:&nbsp;"SPX372928/MyIPTV"<MyIPTV@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;Re: [SPX372928/MyIPTV] 移动的凤凰台都是720的了，老哥我给你个1080的吧 (#2)





  
测试可用！感谢！
  
甭客气，一起加油儿一起玩儿

**Comment by qwerttvv** [comment]
> 你好，你回邮件是不是按了回复所有人什么的，我收到好几个邮件。。。 钟红卫 广东体育职业技术学院 联系我 &nbsp;
> […](#)
> ------------------&nbsp;原始邮件&nbsp;------------------ 发件人:&nbsp;"qwerttvv"<notifications@github.com&gt;; 发送时间:&nbsp;2020年6月29日(星期一) 中午11:05 收件人:&nbsp;"SPX372928/MyIPTV"<MyIPTV@noreply.github.com&gt;; 抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;; 主题:&nbsp;Re: [SPX372928/MyIPTV] 移动的凤凰台都是720的了，老哥我给你个1080的吧 (#2) 测试可用！感谢！ 甭客气，一起加油儿一起玩儿 — You are receiving this because you are subscribed to this thread. Reply to this email directly, view it on GitHub, or unsubscribe.

`You are receiving this because you are subscribed to this thread.`

**Comment by rufan321** [comment]
这两天香港的电视台都KO了，难呀

**Comment by qwerttvv** [comment]
> 这两天香港的电视台都KO了，难呀

有一个福建的可以用

**Comment by qwerttvv** [comment]
http://223.110.
@
245.136/PLTV/3/224/
@
322122
@
6975/
@
index.m3u8

避免搜索死的快，你自己去掉换行和at
