### ISSUE TITLE
北方广电CDN域名更新

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#20]
北方广电CDN的域名更新了，现在是“httplive.slave.bfgd.com.cn”
另外我稍微扫了一下源，减少了一堆数字频道和CCTV-12，增加了浙江卫视（programid=4200000094），此外部分频道升级到了高清版（比如辽宁公共）
![image](https://user-images.githubusercontent.com/46863206/110463845-5f65d800-810d-11eb-8971-049fee18dddf.png)

**Comment by SPX372928** [comment]
收到，明后天看看

**Comment by SPX372928** [comment]
已更新
