### ISSUE TITLE
福建PLTV下面的几个厦门台依旧能看，就是缓冲IP得换

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#24]
福建PLTV下面本来不用缓冲IP能看的厦门卫视（3221226781）、厦门四个地市台以及宁德二套（3221226635）都还是可以正常收看的，只是缓冲IP不一样
测试了一下39.135.53.194-39.135.53.197这个区间的缓冲IP都能看
目前暂时不清楚这套缓冲IP下面能具体有几个频道

**Comment by SPX372928** [comment]
感谢，这个我知道，只是没加。。。

**Comment by Phineario** [comment]
下午花点时间扫了下源，发现新增了一些原来没有的源（比如福建教育台和甘肃卫视高清）
[福建CDN不重复（id不重复）.txt](https://github.com/SPX372928/MyIPTV/files/6264385/CDN.id.txt)

**Comment by Phineario** [comment]
> 感谢，这个我知道，只是没加。。。

下午花点时间扫了下源，发现新增了一些原来没有的源（比如福建教育台和甘肃卫视高清）
[福建CDN不重复（id不重复）.txt](https://github.com/SPX372928/MyIPTV/files/6275387/CDN.id.txt)
