### ISSUE TITLE
河南移动CDN复活了

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#25]
河南移动ＣＤＮ复活了，就是缓冲IP变成了ipv6的（[2409:8087:4401:20:1:f01:1000:a]和[2409:8087:4401:20:1:f01:1:41]）
我这边教育网看着还蛮流畅的
目前扫出了92个不重复的频道，不知道还未来还会不会发掘新的IP

**Comment by SPX372928** [comment]
可惜我现在用的专线不支持v6，晚上有时间就想看看剧，所以最近也没怎么更

**Comment by Phineario** [comment]
我先把我扫到的一些源传上来吧
可惜我教育网不是河南的，直接访问域名无法直接返回缓冲IP，而且ipv6的IP也不知道扫源该怎么扫，所以目前就只能找到这两个缓冲IP
[河南CDN-220057.txt](https://github.com/SPX372928/MyIPTV/files/6229550/CDN-220057.txt)
