### ISSUE TITLE
浙江+陕西CDN更新

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#26]
浙江和陕西的CDN新增了几个频道，其中浙江两个失效的频道因为放一段就不动了所以没加分辨率
[浙江CDN新增频道.txt](https://github.com/SPX372928/MyIPTV/files/6293675/CDN.txt)
[陕西CDN新增频道.txt](https://github.com/SPX372928/MyIPTV/files/6293677/CDN.txt)

**Comment by SPX372928** [comment]
已更新
