### ISSUE TITLE
广西PLTV移动CDN版get dead了

### ISSUE THREAD

**Issue by zekron** [SPX372928/MyIPTV#29]
昨天还能用，今天就莫名用不了了

**Comment by cuczimu** [comment]
撸挂很正常的，看别的。

**Comment by SPX372928** [comment]
加ip， 39.135.33.209或39.135.33.12 这俩会跳到别的ip分流，这样的ip单单这个段就有大概几十甚至上百个，后面的88888888随便改，CCTV13 8M1080,http://39.135.33.209/cdnrrs.gx.chinamobile.com/PLTV/3/224/3221225787/index.m3u8 已更新到文件中
