### ISSUE TITLE
大佬你那个免翻链接在国内有些地方还是用不了，我给你几个全国任意运营商都能用的

### ISSUE THREAD

**Issue by qwerttvv** [SPX372928/MyIPTV#3]
https://beijing-iptv.vercel.app/IPTV-Unicom-Multicast.m3u

https://cdn.jsdelivr.net/gh/qwerttvv/Beijing-IPTV/IPTV-Unicom-Multicast.m3u

https://raw.staticdn.net/qwerttvv/Beijing-IPTV/master/IPTV-Unicom-Multicast.m3u

https://raw.fastgit.org/qwerttvv/Beijing-IPTV/master/IPTV-Unicom-Multicast.m3u

类似这种都是任意运营商任意地区都可以用的，vercel需要官网开通一下，其余的照着格式改一下就能用

**Comment by SPX372928** [comment]
感谢！我这里raw.githubusercontent.com用不了，但github pages可以，还以为其他地区也可以这样解决，原来还不行啊。。。
另外我对源的编辑方式不适合直接使用，单个文件的镜像好像意义不大，就找了包括fastgit在内的其他几个镜像，都带有主页，可能更方便些吧。

**Comment by qwerttvv** [comment]
https://hub.fastgit.org/SPX372928/MyIPTV/  这样儿也不赖，国内通用
