### ISSUE TITLE
居然没人留言，路过！谢谢贴主的无私奉献，咪咕已经失效了

### ISSUE THREAD

**Issue by youe360** [SPX372928/MyIPTV#4]

**Comment by SPX372928** [comment]
好像只有移动能直接用，在前面加个ip其他网络就能看了，明天我找找记录补上

**Comment by youe360** [comment]
感谢！另外，我加几个台，1080P的央视风云系列，我自己尝试的，白剽党，不能白剽
CCTV电视指南,http://39.135.19.162:18890/PLTV/88888888/224/3221225673/1/index.m3u8?fmt=ts2hls
CCTV文化精品,http://39.135.19.162:18890/PLTV/88888888/224/3221225675/1/index.m3u8?fmt=ts2hls
CCTV女性时尚,http://39.135.19.162:18890/PLTV/88888888/224/3221225699/1/index.m3u8?fmt=ts2hls
CCTV第一剧场,http://39.135.19.162:18890/PLTV/88888888/224/3221225702/1/index.m3u8?fmt=ts2hls
CCTV怀旧剧场,http://39.135.19.162:18890/PLTV/88888888/224/3221225765/1/index.m3u8?fmt=ts2hls
CCTV风云剧场,http://39.135.19.162:18890/PLTV/88888888/224/3221225700/1/index.m3u8?fmt=ts2hls
CCTV风云音乐,http://39.135.19.162:18890/PLTV/88888888/224/3221225698/1/index.m3u8?fmt=ts2hls
CCTV风云足球,http://39.135.19.162:18890/PLTV/88888888/224/3221225734/1/index.m3u8?fmt=ts2hls
CCTV高尔夫网球,http://39.135.19.162:18890/PLTV/88888888/224/3221225674/1/index.m3u8?fmt=ts2hls
CCTV老故事,http://39.135.19.162:18890/PLTV/88888888/224/3221225677/1/index.m3u8?fmt=ts2hls
CCTV世界地理,http://39.135.19.162:18890/PLTV/88888888/224/3221225733/1/index.m3u8?fmt=ts2hls
CCTV兵器科技,http://39.135.19.162:18890/PLTV/88888888/224/3221225676/1/index.m3u8?fmt=ts2hls
CCTV新科动漫,http://39.135.19.162:18890/PLTV/88888888/224/3221225678/1/index.m3u8?fmt=ts2hls
CCTV中学生,http://39.135.19.162:18890/PLTV/88888888/224/3221225663/1/index.m3u8?fmt=ts2hls

**Comment by SPX372928** [comment]
贵州移动19.16*的还有几个，一扫就出来，不过容易一起挂，就没加
