### ISSUE TITLE
麻烦告知一下

### ISSUE THREAD

**Issue by chanshgit** [SPX372928/MyIPTV#44]
请问频道名后面的3M、4M代表的是码率吗 是通过什么工具得到的

**Comment by Phineario** [comment]
码率用Ipotplayer打开看一下就行了，图中打红圈的那个“位率”就是码率
![image](https://user-images.githubusercontent.com/46863206/133905366-be240fa9-a6b8-4936-85f9-bf64c4ad920d.png)
另外还有一个方法就是Alt+A用potplayer的录制功能录制一段ts流，然后去查看文件属性的“详细信息”一栏，“视频”下面的“数据速率”（高亮的）就是码率
![image](https://user-images.githubusercontent.com/46863206/133905471-764fac19-0e68-4d3e-987a-54f2cb6d52bf.png)

**Comment by SPX372928** [comment]
大部分是在用pot播放时看播放信息来手动编辑，少部分是录制后拿mediainfo看的，有些在元数据里是直接标明码率的，视频也只在已标明码率上下很小的范围内波动

**Comment by chanshgit** [comment]
感谢回复，原来是通过播放器一个个添加的，太过麻烦了吧，可以试试用ffprobe查看视频流的码率和分辨率，不过码率也不是百分之百能有结果。准备写个小工具来做这件事。

发自我的 iPhone

**Comment by SPX372928** [comment]
> 感谢回复，原来是通过播放器一个个添加的，太过麻烦了吧，可以试试用ffprobe查看视频流的码率和分辨率，不过码率也不是百分之百能有结果。准备写个小工具来做这件事。 发自我的 iPhone
> […](#)
> 在 2021年9月19日，下午8:56，不靠谱 ***@***.***> 写道： 大部分是在用pot播放时看播放信息来手动编辑，少部分是录制后拿mediainfo看的，有些在元数据里是直接标明码率的，视频也只在已标明码率上下很小的范围内波动 — You are receiving this because you authored the thread. Reply to this email directly, view it on GitHub, or unsubscribe. Triage notifications on the go with GitHub Mobile for iOS or Android.

一开始是确定频道名的时候顺手加上，后来习惯了也不觉得麻烦了
