### ISSUE TITLE
天脉聚源已挂

### ISSUE THREAD

**Issue by Sing-0109** [SPX372928/MyIPTV#5]
广东移动无法访问，不知道其它地方情况怎么样

**Comment by SPX372928** [comment]
的确挂了，连内置天脉EPG的百川、DIYP都获取不到节目信息了

**Comment by Sing-0109** [comment]
天脉不知道是不是换接口了，迟点看看有没有新的接口出来，先用着tvmao的吧，虽然不太准，好过没有吧:(

**Comment by SPX372928** [comment]
恢复了
