### ISSUE TITLE
关于广西桂林PLTV下面的一个慢直播直播源

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#54]
广西桂林PLTV下面的一个慢直播（直播 8M1080，ID：3221225872），直播的是广西南宁的南宁国际会展中心，具体的拍摄地点和摄像头位置如下：
![image](https://user-images.githubusercontent.com/46863206/148635567-a9a5e618-34c5-4860-8aaa-fcf383a92479.png)
![image](https://user-images.githubusercontent.com/46863206/148635574-d6ac00a0-d3c8-492a-b3f5-19c358b62095.png)
请及时更新，谢谢！
另外稍微扯点别的，我去年9月的时候说过“湖南IAS长沙电信ip版”[又复活了来着](https://github.com/SPX372928/MyIPTV/issues/43)，刚刚去看的时候发现这套源又失效了，不得不说这套源真的短命。

**Comment by SPX372928** [comment]
已更新，感谢！
