### ISSUE TITLE
建议本仓库注明版权信息

### ISSUE THREAD

**Issue by daylighti** [SPX372928/MyIPTV#55]
尊敬的维护者，您好：
我是河南某高校的校园IPTV系统维护人员。建议您可以在readme文件当中注明不要用于商业用途，这样对您和其他人都有好处。

其实，最初其实各大高校的电视服务并不是屏蔽对外访问的。但随着带宽滥用和其他不合理用途的增多。有许多学校的网络出口时常被该类服务完全占满，因此，迫不得已停止了对外服务。
就我所在团队负责的两个学校而言，它们的源在网络上已经被分享了非常多次了，尤其是恩山无线论坛，也早已经不知道有多少相关的帖子了。在2021年的5月，其中一个学校因为网上的帖子甚至还收到了律师函。因此也付出了很大代价。这之间的压力可能是非有关人士无法了解的。
其实从维护者的角度而言，个人真的并不反对将相应的资源用于个人用途。因为知识是无价的，也希望能对个人的生活有帮助。
对于那些滥用的人，个人也想说你们真的不厚道，把地址放到拥有数百万人的电视直播软件中就算了，还靠这个去国外赚钱，真的是服了。满了你的钱包，苦了我们一众高校啊。

很久以前，省内几个学校就达成了共识：在网络上不合理分享的帖子完全消失之前，学校的IPTV内容不会再对外提供服务。

**Comment by qwerttvv** [comment]
老鼠屎哪里都有，但不要因噎废食。

不厚道不地道的人捞偏的同时，有更大的群体实打实的因为你们无私提供的服务得到了非常大的帮助甚至说满足。

胸怀要广阔，就在眼前，jsdelivr和CF提供的服务总是被各种滥用，包括github一定程度上也是一样，诸如此类国内国外比比皆是，但是你没有看到他们因为一些老鼠屎，抛弃了他们的理想和执念，抛弃了他们更多善良的用户。

无论如何，我作为一个普通的观众，感谢你们之前提供的服务，并且无论你们是否愿意恢复，都会送上祝福。

**Comment by SPX372928** [comment]
[加上了](https://github.com/SPX372928/MyIPTV/commit/4ea327365391b9437030cad06e83d6ba4147a7c8)

**Comment by daylighti** [comment]
> 老鼠屎哪里都有，但不要因噎废食。
> 
> 不厚道不地道的人捞偏的同时，有更大的群体实打实的因为你们无私提供的服务得到了非常大的帮助甚至说满足。
> 
> 胸怀要广阔，就在眼前，jsdelivr和CF提供的服务总是被各种滥用，包括github一定程度上也是一样，诸如此类国内国外比比皆是，但是你没有看到他们因为一些老鼠屎，抛弃了他们的理想和执念，抛弃了他们更多善良的用户。
> 
> 无论如何，我作为一个普通的观众，感谢你们之前提供的服务，并且无论你们是否愿意恢复，都会送上祝福。


非常感谢您可以及时回应。其实我校领导也是这么想的。
近期我校也委托了第三方法律机构去跟许多论坛网站沟通。如果最后沟通的结果是可以删除帖子并使相应区域内容不再被搜索引擎抓取到的话（笼统的来说就是解决版权问题），
