### ISSUE TITLE
你好 请教个有关香港cdn源的问题

### ISSUE THREAD

**Issue by huanzhiyi** [SPX372928/MyIPTV#6]
看了下只有有线新闻一类的台，能否支持如TVB翡翠一类台
是需要香港的服务器转发的吗？
这些是自己的代理源吗？

**Comment by SPX372928** [comment]
那是UTV手机应用里抓的，代理的无线源画质低，其他来源挂得快。。。

**Comment by huanzhiyi** [comment]
好的 感谢告知 主要是TVB翡翠，粤语比较喜欢的一个频道 这类型的确是挂得快而且不清晰  想着有个代理源码自己挂一下就不用整天修改
