### ISSUE TITLE
大家一起来撸挂它们！

### ISSUE THREAD

**Issue by jinshi1234567890** [SPX372928/MyIPTV#61]
人人为我，我为人人。
以下给出的直播源经过精简，主要是删除了标清频道，省内地方频道以及分辨率低的频道还有部分本人不喜欢的频道，需要全的可以自己去扫。没有标注音频采样率的均为48000Hz。
(1)[福建移动rtsp.xlsx](https://github.com/SPX372928/MyIPTV/files/8330011/rtsp.xlsx)
(2)6060端口的外省ipv6亦可访问。[福建PLTV福州移动ip版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330014/PLTV.ip.xlsx)
(3)[广西易视腾柳州移动ip版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330015/ip.xlsx)
(4)[贵州PLTV移动CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330019/PLTV.CDN.xlsx)
(5)看样子每过一年就会更改一次id，主要是针对8M和2.5M码率的频道，原有的id为某个时间点的缓存。[黑龙江PLTV移动CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330020/PLTV.CDN.xlsx)
(6)缺少的频道可去恩山购买，把里面的内网地址替换成抚顺ip即可。[辽宁联通rtsp.xlsx](https://github.com/SPX372928/MyIPTV/files/8330022/rtsp.xlsx)
(7)[山东SNM移动CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330024/SNM.CDN.xlsx)
(8)[陕西PLTV移动ip版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330025/PLTV.ip.xlsx)
(9)地址中id一定要出现两次，不要随意精简，否则会出错。只扫和收录有规律的，目测基本上涵盖了该有的频道，没有的频道上网去找。[易视腾CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330026/CDN.xlsx)
(10)[爱尚电信CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330027/CDN.xlsx)
(11)有UA限制，可在原有UA后面空一格再加上 ZTE 即可，实在不行只保留 ZTE （这样修改UA可能会造成其他链接无法播放，懂技术的话最好开代理）。全国各地各运营商均有服务器，理论上不用担心卡顿不流畅。目前发现的问题是，部分频道(也有可能是所有频道，没有逐一测试)间歇性丢包和掉线。[北京PLTV移动CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330028/PLTV.CDN.xlsx)
(12)[江西广电CDN版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330030/CDN.xlsx)
(13)[四川易视腾成都移动ip版.xlsx](https://github.com/SPX372928/MyIPTV/files/8330032/ip.xlsx)
(14)大部分频道已失效，只是提供一些地址格式供大家参考。[中国电视直播源(备份).txt](https://github.com/SPX372928/MyIPTV/files/8330034/default.txt)

**Comment by SmartYou1995** [comment]
真棒👍

**Comment by clske** [comment]
大街源，迟早挂，用了还得换，路过

**Comment by SingTsang** [comment]
可以啊，兄弟，你这个够全的

**Comment by SPX372928** [comment]
辛苦！

**Comment by microten** [comment]
北京的资源已经挂了 不能用

**Comment by jinshi1234567890** [comment]
> 北京的资源已经挂了 不能用

**Comment by jinshi1234567890** [comment]
我这里能用，非北京地区非移动用户。
![1](https://user-images.githubusercontent.com/102206867/160214198-1c29142d-0a9f-4bc0-b9e5-9ffe5e4f8e0f.jpg)
![2](https://user-images.githubusercontent.com/102206867/160214204-7ec4a549-8e92-4312-afd1-a90c145be767.jpg)

**Comment by jinshi1234567890** [comment]
我这里能用，非北京地区非移动用户。
![1](https://user-images.githubusercontent.com/102206867/160214306-509e5b2f-6567-45e0-bd17-225ca78b77e5.jpg)
![2](https://user-images.githubusercontent.com/102206867/160214316-df67f836-43fa-4e25-aac5-1b1a1a557d88.jpg)

**Comment by jyuan15** [comment]
电信可以用北移和爱尚，但移动不行

**Comment by jinshi1234567890** [comment]
> 电信可以用北移和爱尚，但移动不行 另外，福建rtsp也可以用 183.252.176.54 这个ip

我这里是全网通用，不同地区不同运营商可能有所限制。关于福建移动rtsp，我提供的那个ip打开后会自动跳转到183.252.x.x，个人认为这样要比较好，避免多个人同时访问一个ip造成卡顿。

**Comment by clske** [comment]
> 北京的资源已经挂了 不能用

这套可以用，楼主都给方法了，需要修改user-agent的播放器。

**Comment by microten** [comment]
> 

我修改了 填上ZTE了 没用
我是在电视上看 你用的什么播放器

**Comment by jinshi1234567890** [comment]
> > 
> 
> 我修改了 填上ZTE了 没用 我是在电视上看 你用的什么播放器

确认一下，域名是：ywotttv.bj.chinamobile.com，不是otttv.bj.chinamobile.com。尝试切换播放器的解码方式（如果有这个选项的话），如果不行试试别的播放器。我用的是DIYP影音，解码方式切换为“硬解”（其实是硬解+）后，画面有点发白同时伴随着卡顿，老电视安卓4.X。手机上用MX Player不需要切换解码方式即可播放，当然切换为其他解码方式同样可以播放。

**Comment by microten** [comment]
> 

没错 就是这么弄得 我用的是百川影音 我换diyp试试 是不是北京移动的宽带用不了这个呢

**Comment by microten** [comment]
> 

我用diyp试了一下 果然可以了 看来百川的user agent 不好用

**Comment by jinshi1234567890** [comment]
> > 
> 
> 我用diyp试了一下 果然可以了 看来百川的user agent 不好用

用Perfect Player(包名：com.niklabs.pp)无需修改UA就可以播放，刚刚发现的。

**Comment by clske** [comment]
福建移动rtsp，IP段不行了，不知道是整体封省外还是单纯失效

**Comment by qzlovetv** [comment]
> 福建移动rtsp，IP段不行了，不知道是整体封省外还是单纯失效

没失效，福建移动的流量和宽带都能看

**Comment by qwerttvv** [comment]
[易视腾CDN版](https://github.com/SPX372928/MyIPTV/files/8330026/CDN.xlsx)

请问下这个id是扫的还是哪里抓的啊

**Comment by jinshi1234567890** [comment]
> [易视腾CDN版](https://github.com/SPX372928/MyIPTV/files/8330026/CDN.xlsx)
> 
> 请问下这个id是扫的还是哪里抓的啊
> 
> @jinshi1234567890

在 Windows 用 IPTV Checker 扫，每次导入1万个地址扫，20线程两三分钟就扫完。中间犯过不少错误，比如精简过地址和一次就导入10万个地址导致漏过有效id和掺入了大量无效id并且花费了大量时间。单次1万个地址只需两三分钟，但单次10万个地址却要一个多小时，也有可能是我电脑配置低的问题，所以一次不要导入太多，1万个地址就行了。总共扫了300万个地址，耗时8个小时左右，需要极大的耐心。还有不要在看电视高峰期扫，比如20点-22点之间，否则会很慢甚至错过有效id。
当然要是能找到接口，不用这么麻烦，而且也只是扫到了5位数而已，没有规律的id长达19位数，要扫这辈子是不可能扫的。
