### ISSUE TITLE
更新【陕西PLTV西安移动ip版】

### ISSUE THREAD

**Issue by jinshi1234567890** [SPX372928/MyIPTV#67]
补全央视高清并增加央视数字频道。
[陕西PLTV西安移动ip版.xlsx](https://github.com/SPX372928/MyIPTV/files/9690833/PLTV.ip.xlsx)

**Comment by clske** [comment]
感谢分享

**Comment by jinshi1234567890** [comment]
> 补全央视高清并增加央视数字频道。 [陕西PLTV西安移动ip版.xlsx](https://github.com/SPX372928/MyIPTV/files/9690833/PLTV.ip.xlsx)
