### ISSUE TITLE
江西PLTV吉安移动已失效

### ISSUE THREAD

**Issue by LiuYi0526** [SPX372928/MyIPTV#8]
江西PLTV吉安移动已失效

**Comment by SPX372928** [comment]
可以试着扫下ip，最近有点忙，不方便更新

**Comment by Phineario** [comment]
前段时间扫源扫到的几个ip，应该还能用（用的时候记得把结尾的"?fmt=ts2hls"去掉）
39.135.138.5:6610
39.135.138.2:6610
39.135.138.6:6610
39.135.138.8:6610
39.135.138.9:6610
39.135.138.11:6610
39.135.138.12:6610

**Comment by LiuYi0526** [comment]
> 
> 
> 前段时间扫源扫到的几个ip，应该还能用（用的时候记得把结尾的"?fmt=ts2hls"去掉）
> 39.135.138.5:6610
> 39.135.138.2:6610
> 39.135.138.6:6610
> 39.135.138.8:6610
> 39.135.138.9:6610
> 39.135.138.11:6610
> 39.135.138.12:6610

非常感谢！
