### ISSUE TITLE
Can I do mobile call forwarding?

### ISSUE THREAD

**Issue by zhoumo1987** [SPX372928/MyIPTV#81]
### Discussed in https://github.com/SPX372928/MyIPTV/discussions/80

<div type='discussions-op-text'>

<sup>Originally posted by **zhoumo1987** May 26, 2024</sup>
I have several mobile phones that should be for business reasons, so I want to transfer them directly to my main mobile phone.
How can it be achieved?
May I ask for advice?
</div>

**Comment by SPX372928** [comment]
Just google "Call Forwarding Android/IOS".

**Comment by zhoumo1987** [comment]
具体是怎么 操作的呢大佬

**Comment by SPX372928** [comment]
> 具体是怎么 操作的呢大佬

[`智能机一般打开拨号，进入设置就能看见呼叫转移，如果是老年机，应该在通话设置或其他类似名称的设置里，有的藏得深需要自己多翻找几遍。也可以打运营商电话是否有转接功能，或者试试这里的代码 https://baijiahao.baidu.com/s?id=1771127598458508052&wfr=spider&for=pc
