### ISSUE TITLE
关于江苏PLTV直播源中的一个“未知新闻”频道

### ISSUE THREAD

**Issue by Phineario** [SPX372928/MyIPTV#9]
江苏PLTV直播源中新增的“未知新闻”频道（3221227870），是南京市高淳区的新闻频道
有空的时候记得添加以下频道的名称，谢谢！
![image](https://user-images.githubusercontent.com/46863206/106135227-95c14680-61a2-11eb-9a6b-a1f1f25554fd.png)

**Comment by SPX372928** [comment]
感谢！

**Comment by SPX372928** [comment]
已更新
